name: JS Syntax Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🧪 Run basic JS syntax check
        run: |
          echo "Checking all .js files for syntax errors..."
          find . -name "*.js" -not -path "./node_modules/*" | while read file; do
            echo "Checking $file"
            node --check "$file"
          done
